accent = "#ffdd33"
cursor = "#ffdd33"
foreground = "#e4e4e4"
background = "#181818"
selection_foreground = "#ffffff"
selection_background = "#50585d"

color0 = "#282828"
color1 = "#ffdd33"
color2 = "#73d936"
color3 = "#ffdd33"
color4 = "#f5f5f5"
color5 = "#ffdd33"
color6 = "#ffffff"
color7 = "#303540"
color8 = "#96a6c8"
color9 = "#f43841"
color10 = "#95a99f"
color11 = "#d9ba73"
color12 = "#95a99f"
color13 = "#ffdd33"
color14 = "#73d936"
color15 = "#e4e4e4"
